services:
  elastic:
    image: elasticsearch:8.11.0
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  
  kibana:
    image: kibana:8.11.0
    ports:
      - 5601:5601
    restart: always
    volumes:
      - kibana_data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - xpack.security.enabled=false

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data
    restart: always

  app:
    build: app
    ports:
      - 80:80
    restart: always

  server:
    build: server
    ports:
     - 8080:8080
    command: uvicorn slsher_server:api --host 0.0.0.0 --port 8080
  
  services:
    build: server
    command: celery -A slsher_services worker --loglevel INFO
  
volumes:
 elasticsearch_data:
 kibana_data:
 redis_data:
 neo4j_data: