services:
  elastic:
    image: elasticsearch:8.11.0
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  
  kibana:
    image: kibana:8.11.0
    ports:
      - 5601:5601
    restart: always
    volumes:
      - kibana_data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - xpack.security.enabled=false

  app:
    build: app
    ports:
      - 8080:8080
    restart: always
  
volumes:
 elasticsearch_data:
 kibana_data: